# Publish package on release branch if it's tagged with 'v*'

name: release & publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: Publish package
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Build package
        run: |
          python setup.py sdist
          python setup.py bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PERSONAL_TOKEN }}

      # - name: build documentation
      #   run: |
      #     sphinx-apidoc -o docs/ lakeapi

      # - name: publish documentation
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.PERSONAL_TOKEN }}
      #     publish_dir: ./site
